### PR TITLE
Clicking a node highlights its nonmonophylic pair

### LINKED ISSUE #42: Fix alert-of-nonmonophyly when clicking a dot
When you click a dot, you're supposed to get an `alert()` of the nonmonophyletic pair.

That is currently broken.

### PR DESCRIPTION
**Pull request by OmarShehata**
This fixes #42 by refactoring what clicking does. The old code was throwing an error because it was attempting to get input from an html input field that no longer exist.

The new behavior accepts clicks on any leaf node, and will pop up an alert telling you its pair. It will also set all other nodes except for the pair to opacity 0.2 so that it is visually easy to find the pair. Clicking again will reset everything to opacity 1 (clicking on a blue dot will also set opacity to 1). 

I would personally prefer to chuck the alert and just have it toggle the opacity, but I'm keeping it for now in case the biologists' use case is more about just getting the number than seeing it in the tree.

### CODE REVIEW

File: electron/graph.js [hunk 1]
```diff
@@ -122,19 +124,61 @@ function findOutliers(objs, whitelist, found = []) {
 	return found
 }
 
-function onNodeClicked(data) {
-	console.log('Clicked on node point with data:', data)
-
-	let outliers = findOutliers(data.branchset, getWhitelist())
-	console.log('Outliers found:', outliers)
+function ToggleMuteLeaves(doMute){
```
Comment (hawkrives) [inline electron/graph.js]: Please lower-case this function name since it's not a class

Comment (hawkrives) [reply electron/graph.js]: Also let's restructure the argument to be an object so you can see what it means at the callsites:

```js
function toggleMuteLeaves({doMute}) {

// and

toggleMuteLeaves({doMute: false})
```

File: electron/graph.js [hunk 2]
```diff
@@ -122,19 +124,61 @@ function findOutliers(objs, whitelist, found = []) {
...
+			nonmono_pair = pair[0];
+			break;
+		}
+	}
+	// Now let's toggle the non-mono pair green if one was found
+
+	if(nonmono_pair){
+		// If it's already muted, toggle all off 
+		var nodeSVG = document.querySelector("[data-ident='"+data.ident+"']")
+		var pairSVG = document.querySelector("[data-ident='"+nonmono_pair.ident+"']")
```
Comment (hawkrives) [inline electron/graph.js]: Use a template string here, please: 

```js
document.querySelector(`[data-ident='${nonmono_pair.ident}']`)
```

File: electron/graph.js [hunk 3]
```diff
@@ -122,19 +124,61 @@ function findOutliers(objs, whitelist, found = []) {
...
 
-	outliers.forEach(outlier =>
-		document.getElementById(outlier).setAttribute('fill', 'green')
-	)
+function onNodeClicked(data) {
+	if(data.name == "" || nmResults == undefined)
+		return; // We don't care about anything that's not a leaf node
+	// Find the other individual that is nonmonophyletic with this one
+	var nonmono_pair;
+	for(var i=0;i<nmResults.nm.length;i++){
```
Comment (hawkrives) [inline electron/graph.js]: Use a for-of loop, please:

```js
for(let pair of nmResults.nm) {
```

File: electron/graph.js [hunk 4]
```diff
@@ -122,19 +124,61 @@ function findOutliers(objs, whitelist, found = []) {
...
+		var nodeSVG = document.querySelector("[data-ident='"+data.ident+"']")
+		var pairSVG = document.querySelector("[data-ident='"+nonmono_pair.ident+"']")
+		if(nodesMuted){
+			ToggleMuteLeaves(false)
+		} else {
+			// First we set all nodes to muted
+			ToggleMuteLeaves(true);
+			// Except for the one and its pair 
+			nodeSVG.className.baseVal = nodeSVG.className.baseVal.replace("muted","")
+			pairSVG.className.baseVal = pairSVG.className.baseVal.replace("muted","")
```
Comment (hawkrives) [inline electron/graph.js]: Use `pairSVG.classList.remove('muted')`?

File: electron/graph.js [hunk 5]
```diff
@@ -122,19 +124,61 @@ function findOutliers(objs, whitelist, found = []) {
...
+			break;
+		}
+	}
+	// Now let's toggle the non-mono pair green if one was found
+
+	if(nonmono_pair){
+		// If it's already muted, toggle all off 
+		var nodeSVG = document.querySelector("[data-ident='"+data.ident+"']")
+		var pairSVG = document.querySelector("[data-ident='"+nonmono_pair.ident+"']")
+		if(nodesMuted){
```
Comment (hawkrives) [inline electron/graph.js]: Let's replace this global variable with 

```js
if (document.querySelector('.node.leaf.muted')) {
  // …
```

File: electron/graph.js [hunk 6]
```diff
@@ -122,19 +124,61 @@ function findOutliers(objs, whitelist, found = []) {
...
+}
 
-	outliers.forEach(outlier =>
-		document.getElementById(outlier).setAttribute('fill', 'green')
-	)
+function onNodeClicked(data) {
+	if(data.name == "" || nmResults == undefined)
+		return; // We don't care about anything that's not a leaf node
+	// Find the other individual that is nonmonophyletic with this one
+	var nonmono_pair;
```
Comment (hawkrives) [inline electron/graph.js]: Please use camelCase to name variables, and please use `let/const` instead of `var`.

File: electron/graph.js [hunk 7]
```diff
@@ -122,19 +124,61 @@ function findOutliers(objs, whitelist, found = []) {
...
 
-function onNodeClicked(data) {
-	console.log('Clicked on node point with data:', data)
-
-	let outliers = findOutliers(data.branchset, getWhitelist())
-	console.log('Outliers found:', outliers)
+function ToggleMuteLeaves(doMute){
+	var nodes = document.querySelectorAll(".node.leaf")
+	nodesMuted = doMute
+	for(var i=0;i<nodes.length;i++){
```
Comment (hawkrives) [inline electron/graph.js]: What about replacing this whole function body with

```js
const nodes = document.querySelectorAll(".node.leaf")
for (let node of nodes) {
	if (doMute) {
		node.classList.add('muted')
	} else {
		node.classList.remove('muted')
	}
}
```

**Comment by OmarShehata** [comment]
Should be all good now. Tested and it still works!
